export { default as Homepage } from './Homepage';
export { default as Posts } from './Posts';
export { default as Profile } from './Profile';
export { default as LogIn } from './LogIn';
export { default as RegisterForm } from './RegisterForm'
export { default as ErrorMessage } from './ErrorMessage'
export { default as AddPost } from './AddPost'
export { default as EditPost } from './EditPost'
export { default as AddMessage } from './AddMessage'
